# Generated by Django 3.0.5 on 2020-05-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainScreen', '0002_auto_20200504_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='transaction_user',
        ),
    ]
