# Generated by Django 3.0.5 on 2020-05-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainScreen', '0003_auto_20200507_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_direction',
            field=models.IntegerField(choices=[(1, 'Send'), (2, 'Receive')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Entertainment'), (2, 'Utilities'), (3, 'Food'), (4, 'Transport')], default=1),
            preserve_default=False,
        ),
    ]
