# Generated by Django 3.0.5 on 2020-06-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainScreen', '0006_wallet_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='total',
            new_name='wallet_transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_direction',
            field=models.IntegerField(choices=[(1, 'Send'), (2, 'Receive')], default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Entertainment'), (3, 'Utilities'), (4, 'Food'), (5, 'Transport')], default=1),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='revenue',
            field=models.FloatField(default=0),
        ),
    ]
